server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-c2gyaqqsxa2v3nig.us.auth0.com/}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


snippets:
  base-url: ${SNIPPETS_BASE_URL:http://snippets:8080}

auth0:
  audience: ${AUTH0_AUDIENCE:https://snippet-manager}
  domain: ${AUTH0_DOMAIN:dev-c2gyaqqsxa2v3nig.us.auth0.com}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}

streams:
  enabled: true
  formatting:
    key: ps.formatting
    group: formatting-workers
  linting:
    key: ps.linting
    group: linting-workers
  dlq:
    formatting: ps.dlq.formatting
    linting: ps.dlq.linting

newrelic:
  logs:
    enabled: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    root: INFO
    org.springframework.data.redis.stream: DEBUG
    org.springframework.data.redis.serializer: DEBUG
    org.springframework.data.redis.connection: DEBUG
    io.lettuce.core: DEBUG           # pasar a DEBUG si sospech√°s networking
    reactor.core.publisher: INFO
    org.springframework.data.redis: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
