server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-c2gyaqqsxa2v3nig.us.auth0.com/}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


snippets:
  base-url: ${SNIPPETS_BASE_URL:http://snippets:8080}

auth0:
  audience: ${AUTH0_AUDIENCE:https://snippet-manager}
  domain: ${AUTH0_DOMAIN:dev-c2gyaqqsxa2v3nig.us.auth0.com}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}

streams:
  enabled: true
  formatting:
    key: ${STREAMS_FORMATTING_KEY:ps.formatting}
    group: ${STREAMS_FORMATTING_GROUP:formatting-workers}
  linting:
    key: ${STREAMS_LINTING_KEY:ps.linting}
    group: ${STREAMS_LINTING_GROUP:linting-workers}
  dlq:
    formatting: ${STREAMS_DLQ_FORMATTING:ps.dlq.formatting}
    linting: ${STREAMS_DLQ_LINTING:ps.dlq.linting}

newrelic:
  logs:
    enabled: true
